### PR TITLE
WIP: launch prep

### PR DESCRIPTION
**Pull request by joehand**
Milestone https://github.com/datproject/dat-foundation-website/milestone/1

Current pages. These pages need content and review:

- [ ] Homepage (owner: @RangerMauve)
   - [x] Double check wording
   - Fill in featured projects
- [x] Chat (owner: @RangerMauve )
   - Touch up wording / links to IRC
- [x] People (owner: @RangerMauve )
   - Who should be here?
- [x] About - Foundation (owner: ???)
- [x] About - History ( owner: @joehand @okdistribute )
- [ ] Explore - Gettingstarted (owner: @todrobbins)
    - Add onboarding guide for folks new to the community
- [x] Explore - Projects (owner: @RangerMauve )
  - Add existing projects to the list
  - Add new projects to the list
  - Migrate [project updates](https://github.com/datproject/project-updates) repo?
- [x] Explore - Modules
  - List modules related to Dat
  - List project pages for alternative implementations

Needed for MOSS. These pages needed to be added/moved from old sites:

- [ ] github/datproject/docs -- Tutorial/Cookbook section covering 5-10 Dat development use cases 
- [x] Community - Projects -- *Area for showcasing Dat-built applications, encourage “dogfooding”* (@rangermauve)
- [ ] ??? -- *New developer on-boarding funnel* (e.g. How can I help? page)
- [ ] ??? -- Process for adding community-driven pages with 2-3 examples
  * Readme examples
  * Examples: Comm-comm page, events page (?)

### CODE REVIEW

**Comment by RangerMauve** [comment]
Built the project so far. Found / fixed a bug in footer navigation. Checked over existing sections to see what was unfinished.

Will look into adding to the navigation for the extra stuff on the list after flushing out some of this stuff.

**Comment by okdistribute** [comment]
@noffle said it could be nice to add the kappa-db workshop to the cookbook, for multiwriter apps. We could stretch that deliverable out over the 5-10 use cases, as well as add the stuff mauve has worked on! Hopefully that's helpful. 

Thanks for organizing this. How long will it take?

**Comment by RangerMauve** [comment]
Not sure yet. It's looking like a couple of weeks at least. 😅 There's a lot of content to get in.

**Comment by RangerMauve** [comment]
Looked at chat, fixed a few bugs, working on updating README with description of how stuff works and updating people.

**Comment by RangerMauve** [comment]
Gonna try to reuse stuff from the old website when possible (like the people list)

**Comment by RangerMauve** [comment]
Ported people from old foundation website to the new one. Gonna go a small draft of modules to get things started then reach out to the community for help.

@todrobbins mind if I take over the projects stuff? Or is there a way we could split that up between us?

Talking to @okdistribute, we're going to aim to have _something_ together for Wednesday. Might put some time over the weekend towards this goal and take next Friday off or something. :P

**Comment by todrobbins** [comment]
@RangerMauve you can take it on if you'd like. I'll keep working on the Get Started page.

**Comment by RangerMauve** [comment]
@todrobbins Sweet, thank you! I'll merge what I have so far into this branch today. 💜

**Comment by RangerMauve** [comment]
Got the projects in. Just did the ones on the old website. Might reach out to the community for adding more with PRs after we get the initial stuff out there.

Gonna start on modules.

**Comment by RangerMauve** [comment]
Not sure what modules to add, but I added some. :P

**Comment by todrobbins** [comment]
@RangerMauve which branch are you working in?

**Comment by RangerMauve** [comment]
@todrobbins I'm working in https://github.com/datproject/dat-foundation-website/pull/126

Gonna add more community projects to the projects page. Also, going to figure out more about how Viewpress and Netlify work because I kinda jumped in without reading up on it. :P

**Comment by RangerMauve** [comment]
Having trouble getting netlify admin thing to work. Gonna put that on hold and focus on projects some more.

**Comment by RangerMauve** [comment]
Are y'all okay with me taking on "Process for adding community-driven pages with 2-3 examples"? I was thinking of including it in a README or a CONTRIBUTING.md or something and linking to it from the website under "community". Maybe call it "Contribute". Or should we have a button somewhere else?

@joehand any clue if @whoisgina had ideas about what to do for that?

**Comment by joehand** [comment]
> Are y'all okay with me taking on "Process for adding community-driven pages with 2-3 examples"? I was thinking of including it in a README or a CONTRIBUTING.md or something and linking to it from the website under "community". Maybe call it "Contribute". Or should we have a button somewhere else?

Sounds good! It'd be good to include the examples.

> Having trouble getting netlify admin thing to work. Gonna put that on hold and focus on projects some more.

We can look at the Netlify admin thing, but its more of a nice-to-have than strict requirement.

**Comment by RangerMauve** [comment]
Gonna remove merging the newsletter and docs from the TODO since it doesn't seem to be part of the MOSS milestones

**Comment by whoisgina** [comment]
> Are y'all okay with me taking on "Process for adding community-driven pages with 2-3 examples"? I was thinking of including it in a README or a CONTRIBUTING.md or something and linking to it from the website under "community". Maybe call it "Contribute". Or should we have a button somewhere else?
> 
> @joehand any clue if @whoisgina had ideas about what to do for that?

My intent was that the project and event content types fulfill this requirement in that any community member can add one or many via the CMS and request approval from an admin. Not "pages" per se, but I wanted to prevent the addition of new pages because that's sort of what got us into our current website situation.

**Comment by RangerMauve** [comment]
Err, why was `/explore/modules` removed?

**Comment by RangerMauve** [comment]
Woot, tests are passing. 😤

**Comment by RangerMauve** [comment]
Went through the code in the old site and it seems that the only link that'll be broken is the about page and maybe some images that others could have linked to.

**Comment by RangerMauve** [comment]
@whoisgina were you able to get netlify's CMS stuff working? I've been having getting to work in https://dat-foundation-next.netlify.com/admin/#/

**Comment by RangerMauve** [comment]
@todrobbins Any luck on the getting started stuff? Is there more stuff to merge in?

**Comment by okdistribute** [comment]
@RangerMauve I was able to get the netlify cms working, you have to change the `branch` variable in `site/.vuepress/public/admin/config.yml`

**Comment by RangerMauve** [comment]
Talked to @joehand today. Stuff for the TODO list to get this done:

- Ask @okdistribute about what she thinks might be missing design wise or any hesitations with releasing
- Reach out to consortium to see how they feel about it
- Worst case, the escape hatch is releasing this as a new dat.land to get the grant finished (hopefully not necessary)

**Comment by RangerMauve** [comment]
Did a once-over for the pages we have so far. Found that the Chat wasn't linked to anywhere, found some broken links in the history page.

No word on the consortium newsletter about the new website.

Only thing that's missing seems to be the getting started page.

**Comment by RangerMauve** [comment]
Working on the getting started page today BTW

**Comment by RangerMauve** [comment]
K, merging and releasing.

**Pull request merged**
