### PR TITLE
Add comm comm to navigation

### LINKED ISSUE #166: Add Comm-Comm to menu
Add link to https://comm-comm.datproject.org/ in the menu

### PR DESCRIPTION
**Pull request by RangerMauve**
Closes #166 

How's this look?

### CODE REVIEW

**Comment by todrobbins** [comment]
Nice! I'm wondering whether we should rethink the menu design a bit. It's really hard to tell where one item ends and another begins:

Screen Shot 2020-02-19 at 4 21 38 PM

Screen Shot 2020-02-19 at 4 21 43 PM

Maybe the container for the menu items needs to be a bit wider? Unique icons in front of each item? What do you think, @RangerMauve?

We should just merge regardless to get the link in there, but also consider the ✨FUTURE✨

**Comment by todrobbins** [comment]
PS: sorry it took me so long to review such a small change 😂

**Review by todrobbins — APPROVED** [review]
it works! thanks!

**Comment by okdistribute** [comment]
Yes, I agree that these drop-down menus aren't ideal. What if there were no dropdown menus, and when you click on the page, it has all those pages linked (or perhaps in the case of About, embedded) within?

**Comment by RangerMauve** [comment]
Yeah, I agree the nav bar is a little iffy, but I have no clue how to improve it.
If anyone has ideas it'd be great to get a PR.

Should this be merged before we improve the nav?

**Pull request merged**
