### PR TITLE
Setting up auto-publish to dat

### PR DESCRIPTION
**Pull request by sammacbeth**
This PR adds a Github action that will build commits to `release` and publish the `site/.vuepress/dist/` folder to a dat site.

This uses the [`@sammacbeth/dat-publisher`](https://github.com/sammacbeth/sams-dat-api/tree/master/packages/dat-publisher) module I wrote for this purpose, based on [the method](https://sammacbeth.eu/blog/2019/05/26/automated-dat-publishing.html) I've been using on my own blog for a while now. The module does the following steps:
 1. Pull the latest version of the site from the dat network.
 2. Load the given secret key to allow writing to the archive.
 3. Sync all file changes from the site build output to the archive.
 4. Rejoin the network and seed for a set period of time to make sure that other seeders have the updated version.

Note, this relies on reliable long-term seeders of the dat, otherwise bad things could happen. However, there is some protection, as if there are no good seeders step 1 should fail. For this site I will have a 24/7 seed running to ensure reliability.

@okdistribute / @RangerMauve I would need help from a project admin to add the secret key for the dat ([see the docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets))

### CODE REVIEW

**Comment by RangerMauve** [comment]
LGTM! I'm not sure who has the secret keys though. @joehand ?

**Review by RangerMauve — APPROVED** [review]

**Comment by sammacbeth** [comment]
We can either publish to the previous `datproject.org` archive if someone has the keys, or use the new key pair I created at `dat://3e7405dbc026be44f103b42cb3383e51ffab51aada8b58608347edc0a8f2ecce`

**Comment by joehand** [comment]
Yes, I have key for `dat://60c525b5589a5099aa3610a8ee550dcd454c3e118f7ac93b7d41b6b850272330/`. Can share, whats the easiest way to do that?

[Edit: Finished reading PR]

Added private key for the `60c` public key in Github secrets as `private_key`.

**Comment by sammacbeth** [comment]
> 
> 
> Yes, I have key for `dat://60c525b5589a5099aa3610a8ee550dcd454c3e118f7ac93b7d41b6b850272330/`. Can share, whats the easiest way to do that?

If you could add it as an encrypted secret on this repo with the variable named `DAT_SITE_SECRET_KEY` that should do the trick!
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets

**Comment by joehand** [comment]
Okay, added `DAT_SITE_SECRET_KEY`!

**Comment by RangerMauve** [comment]
Yoooo! It's working! <3 <3

Thank you for putting this together. 😁
Feel free to merge this in whenever @sammacbeth.

**Comment by okdistribute** [comment]
bomb yes, this works!

**Comment by sammacbeth** [comment]
After merge dat DNS is also working :)

Screenshot 2020-01-23 at 11 04 22

**Comment by okdistribute** [comment]
nice job @sammacbeth !

**Pull request merged**
