### PR TITLE
Improve project list display on low resolutions

### PR DESCRIPTION
**Pull request by k-nut**
I was browsing the page on my mobile phone and noticed that the projects were overflowing the container and were showing very small images.

Therefore, this PR does two things (split into two commits):
- It replaces the grid with a flexbox and lets the projects resize on demand (see the first commit message for more rationale)
- It changes the image display so that they are displayed as large as possible in the project card without being cropped.

 Let me know if you agree that this is an improvement or if you see any unintended side effects 🙂

| Before | After |
|--------|-------|
|  before |    after |

### CODE REVIEW

**Review by RangerMauve — APPROVED** [review]
Looks good to me, I'll merge it this weekend if nobody else has concerns.

**Comment by okdistribute** [comment]
awesome! thanks so much!

**Review by martinheidegger — DISMISSED** [review]

**Comment by k-nut** [comment]
Ah shoot, I just realized that this does not look great in Safari since it does not support the `gap` property for flexbox yet. Please don’t merge this yet, I’ll push another commit that replaces the gap with a regular margin which should be supported everywhere.

**Comment by k-nut** [comment]
Ok, I pushed another commit that replaces the `gap` with a regular `margin`. When testings in Chrome I got confused by something though. The css for the `projects-index_*` classes is defined in both `site/explore/get-started/index.md` and `site/explore/projects/index.md`. It seems to be duplicated but I only changed it in `projects`. Now Chrome is still picking up the rules from the `get-started` file. Should I replace it in both instances or can one of them even be deleted?
Sorry about the confusion, this looked so straightforward to begin with ;)

**Comment by RangerMauve** [comment]
Thanks for following up and testing this @k-nut 

I'm not sure whether deleting or duplicating is the right way forward there. Does the deletion route still work on all the pages?

**Comment by k-nut** [comment]
My current understanding is that maybe one could delete the whole `get-started` folder in `site/explore`. This is along with the page's content at `site/_data/explore/get-started.yml`

This is what the page currently looks like: https://dat.foundation/explore/get-started/ so I would assume that this is some kind of stub that is not actually used? 

Note that I got there by putting in the URL manually,  the `Get Started` menu item in the top navigation actually does not even link to this page, it rather links to [this external guide](https://docs.dat.foundation/docs/intro).

**Comment by RangerMauve** [comment]
Ah! Good catch, I think that was a WIP when the website was being redesigned. Feel free to remove it.

**Comment by k-nut** [comment]
Ok, I pushed another commit which removes the layout and content for that page. Should be read for a final review now :)

**Review by RangerMauve — APPROVED** [review]
Sweet thank you for working through this!

I'll merge it this weekend unless something else comes up. 💜

**Comment by RangerMauve** [comment]
Thanks again for getting this through @k-nut !

**Pull request merged**
